5393 navbar menu responsive
samvera/hyrax pull request #5395
Opened 2022-01-27 17:08 UTC by mathewjordan

Fixes #issuenumber ; refs #issuenumber

Present tense short summary (50 characters or less)

More detailed description, if necessary. Try to be as descriptive as you can: even if you think that the PR content is obvious, it may not be obvious to others. Include tracebacks if helpful, and be sure to call out any bits of the PR that may be work-in-progress.

Description can have multiple paragraphs and you can use code examples inside:

``` ruby
class PostsController
  def index
    respond_with Post.limit(10)
  end
end
```

Changes proposed in this pull request:
*
*
*

Guidance for testing, such as acceptance criteria or new user interface behaviors:
*
*
*

@samvera/hyrax-code-reviewers

2022-01-27 19:51 UTC, adamjarling approved these changes
Way better!

2022-01-27 19:52 UTC, adamjarling commented on app/assets/stylesheets/hyrax/_styles.scss
> -.navbar {
Nice to see this stuff get thinned out.

2022-01-27 19:53 UTC, adamjarling commented on app/assets/stylesheets/hyrax/dashboard.scss
> -
I fought with removing and adding this a few times.  Glad to see you got the `fixed-top` implementation going.

2022-01-27 19:57 UTC, adamjarling requested changes
Actually @mathewjordan Can you take a look at this on the Dashboard page?   This is what I was fighting with when working on the Sidebar issue yesterday.

![image](https://user-images.githubusercontent.com/3020266/151434091-2a365e3b-1a83-455c-875c-a1afd0337fef.png)

The sidebar tucks underneath the fixed-top nav bar.

2022-01-27 20:03 UTC, mathewjordan commented
> 

Oh yeah @adamjarling. Likely something in that sidebar that is being too explicit. I'll look at that.

2022-01-28 15:26 UTC, mathewjordan commented
@adamjarling This should be good now.

2022-01-28 16:47 UTC, adamjarling approved these changes
Lookin good.

2022-01-28 16:58 UTC, merged