Update Dashboard cards UI and rows/col layout
samvera/hyrax pull request #5411
Opened 2022-01-28 17:15 UTC by adamjarling

Fixes #5401 

Slight updates to the Dashboard page UI. 

![image](https://user-images.githubusercontent.com/3020266/151591844-76601d10-eefd-49ee-94ab-3fc3effefa16.png)

Changes proposed in this pull request:
* Update classnames to match BS4 for Card component and Layout rows/cols
* Added a helper wrapper class to achieve `.row` spacing (which got changed to default no spacing in BS4)

Guidance for testing, such as acceptance criteria or new user interface behaviors:
* Visit the Dashboard page

@samvera/hyrax-code-reviewers

2022-01-28 17:18 UTC, adamjarling commented on app/assets/stylesheets/hyrax/_styles.scss
> +/*
Fixing

2022-01-28 18:33 UTC, mathewjordan requested changes
Looks great. Just one note regarding row spacing.

2022-01-28 18:33 UTC, mathewjordan commented on app/assets/stylesheets/hyrax/_styles.scss
> +  }
This works well until we get to smaller viewports and the wrapping row's vertical spacing doesn't matter as much as a columns. What if it was done this way? 

```suggestion
  .row > .col {
    margin-bottom: 1rem;
  }
```

2022-01-31 14:24 UTC, adamjarling commented
@mathewjordan Made the update to the row spacing you recommended, fyi.

2022-01-31 14:26 UTC, mathewjordan approved these changes
👍

2022-01-31 14:39 UTC, merged