Geonames labels
samvera/hyrax pull request #5493
Opened 2022-03-04 17:37 UTC by dlpierce

Fixes #1065, #3269

Retrieves, indexes and displays the full location label

Previously when indexing the Based Near/Location field on works, only the city name was available as it was all that is available in the rdf data that was retrieved. This PR add a service that retrieves a full label from another Geonames endpoint via questioning authority, caching the results locally. That service is then used when creating the solr doc and rendering the edit form.

Geonames wants a username to use this service. This is defined in `config/initializers/hyrax.rb` as `config.geonames_username = Qa::Authorities::Geonames.username = '{username}'` to set the user in Qa at the same time.

Changes proposed in this pull request:
* Add service based on Qa::Authorities::Geonames to supply a full label
* Index that full label
* Display that full label on the work edit form

Guidance for testing, such as acceptance criteria or new user interface behaviors:
* Creating a work with a location
* Verify full label (e.g. City, State, Country) is shown on work details and edit form

@samvera/hyrax-code-reviewers

2022-03-14 15:07 UTC, elrayle commented
I used this branch to set a location and got an error while saving the new work...

![image](https://user-images.githubusercontent.com/6855473/158201098-638201ca-772c-4cfd-adf0-0cc4a818e1fc.png)

2022-03-14 16:01 UTC, elrayle requested changes
I'm seeing an error when trying to run this.

2022-03-14 20:57 UTC, elrayle commented
PR #5533 fixes the issue where <frozenError> prevents canonicalize from returning the string version of the URI.  This should unblock this PR.

2022-03-22 18:56 UTC, dlpierce commented
Removed configuration changes as they were unneeded.

2022-03-22 20:30 UTC, elrayle approved these changes
This will significantly improve the usefulness of the Location lookups.

2022-03-22 20:30 UTC, merged