Removes icons from Works dashboard actions dropdown menu
samvera/hyrax pull request #5508
Opened 2022-03-08 20:27 UTC by sdellis

Fixes #5506 ; refs #5490

@samvera/hyrax-code-reviewers

2022-03-09 14:20 UTC, hackartisan requested changes

2022-03-09 14:20 UTC, hackartisan commented on app/views/hyrax/my/_work_action_menu.html.erb
>            <span> <%= t("hyrax.dashboard.my.action.edit_work") %> </span>
Do we still need the spans once the icons are gone?

2022-03-10 16:30 UTC, elrayle submitted a review, later dismissed
Looks good to me. 

I noticed that Works use "Edit Work" and Collections use "Edit collection".  A follow-on PR to make those consistent would be good.

2022-03-10 16:32 UTC, hackartisan approved these changes

2022-03-11 16:46 UTC, sdellis commented
<img width="1539" alt="Screen Shot 2022-03-11 at 11 44 44 AM" src="https://user-images.githubusercontent.com/609368/157910597-e9739021-736d-49ea-bb5e-dc9e31cd81b1.png">
<img width="1530" alt="Screen Shot 2022-03-11 at 11 41 11 AM" src="https://user-images.githubusercontent.com/609368/157910601-a9c49b48-cd8b-4cf0-b90b-4ec399be2e66.png">

2022-03-11 21:37 UTC, elrayle requested changes

2022-03-11 21:37 UTC, elrayle commented on app/views/hyrax/my/works/_list_works.html.erb
> +    <% if document.date_modified.nil? %>
I think the reason something like this wasn't done before is that date_modified and date_uploaded are core fields and are set by the system, not the user.  I wonder if you can put just the change to this file in a separate PR.  Everything else looks good to go.  I'd like to think about this change.

2022-03-14 13:37 UTC, sdellis commented
@elrayle I extracted the date formatting from this PR, so this is ready for final review. Will create a new PR for that one.

2022-03-14 13:54 UTC, elrayle approved these changes
Thanks for getting this in place.  These consistency updates to the UI will really improve the user experience.

2022-03-14 13:58 UTC, merged