Find permission templates via their admin set relation
samvera/hyrax pull request #5514
Opened 2022-03-09 18:49 UTC by hackartisan

Without this fix the form just always uses the default permission template behavior

closes #5460

2022-03-09 19:49 UTC, hackartisan commented
I'm honestly not sure what the expectation means on the controller test I changed. But this is what I observe in a working development environment. The bug and the test values were introduced at the same time (in https://github.com/samvera/hyrax/pull/5050) so I think it's fair to assume the test was checking for the fallthrough (no permission template found) defaults rather than the default adminset defaults. Review from someone more familiar with the meaning of these permissions would be very helpful.

2022-03-10 15:03 UTC, elrayle requested changes
This is a good fix.  I have one request for the works controller spec.

2022-03-14 16:45 UTC, elrayle commented
Does this fix Issue #5462 editing a parent work error OR #5460 can't select embargo on work?

2022-03-14 18:06 UTC, elrayle approved these changes

2022-03-14 18:06 UTC, merged

2022-03-15 14:12 UTC, elrayle commented
Also fixes #5467 Sharing tab does not display on works