Update depositors (proxies, transfers) synchronously
samvera/hyrax pull request #5553
Opened 2022-03-17 19:54 UTC by hackartisan

supercedes #5537 
follow-up to #5529 and #5550
closes #5457 

Deprecates ContentDepositorChangeEventJob which called ChangeContentDepositorService, replacing them with a service that does the work and then backgrounds the event logging.

Follow-on work will move file set updates to a new background job, since there might be a lot of file sets. Issue to be created, linked here.

2022-03-17 21:06 UTC, hackartisan commented
This should be in draft until #5550 is merged and rebased on that PR.

2022-03-18 14:43 UTC, elrayle requested changes
This is fantastic.  There is a lot in this PR and I appreciate all the time it took to get this right.

There is a request for one new test and a question about the order of steps for work_create transaction.

2022-03-18 16:08 UTC, hackartisan commented on lib/hyrax/transactions/work_create.rb
>                         'work_resource.add_file_sets',
Oh, good point with the order of the steps!! And I added the test.

2022-03-18 20:39 UTC, elrayle approved these changes
Thanks for reordering the work_create steps and getting in the test.  This was quite a slog, but well done.

2022-03-18 20:41 UTC, merged