Valkyrize batch editing
samvera/hyrax pull request #5864
Opened 2022-09-14 21:30 UTC by cjcolvar

This PR has changes that allow batch editing to work in valkyrized hyrax.
Changes proposed:
- Add `ResourceBatchEditForm` based on `BatchEditForm` and `ResourceForm` to be used when `use_valkyrie` is true
- Handle updating each batch item using new form and work update transaction

This PR is built on top of #5863 so will need to be rebased after it is merged.
Fixes #5797

2022-09-14 22:41 UTC, no-reply commented on app/controllers/concerns/hyrax/works_controller_behavior.rb
> +          'work_resource.change_depositor' => { user: ::User.find_by_user_key(form.on_behalf_of) },
is this related here, or cruft from your other PR?

2022-09-14 22:45 UTC, no-reply commented on app/controllers/concerns/hyrax/works_controller_behavior.rb
> +          'work_resource.change_depositor' => { user: ::User.find_by_user_key(form.on_behalf_of) },
i think this is the cause of the test failures.

2023-06-01 13:36 UTC, alishaevn requested changes
the koppie app is working, but the hyrax app is not. is that your expectation? or do you have other work from this branch that hasn't been pushed?

2023-06-02 17:02 UTC, cjcolvar commented
Sorry, it has been a long time since I've worked on this so I don't recall the exact state where I left it.  I checked and I believe that I've pushed everything for this branch.  I don't have any idea when I'll be working on this again so anyone is free to take what's useful and carry the effort forward.

2023-06-05 17:50 UTC, alishaevn submitted a review, later dismissed

2023-09-08 17:43 UTC, tpendragon commented
Closed, this got fixed in #6148

2023-09-08 17:43 UTC, closed without merging