Make Google Private Key accessible from the ENV.
samvera/hyrax pull request #6063
Opened 2023-05-16 22:44 UTC by orangewolf

This makes K8S deploys and dynamic configuration for Hyku easier.

@samvera/hyrax-code-reviewers

2023-05-16 23:36 UTC, alishaevn requested changes

2023-05-16 23:36 UTC, alishaevn commented on app/services/hyrax/analytics/google.rb
> +        # PRIVA_KEY_VALUE. VALUE htakes precedence.
```suggestion
        # PRIVATE_KEY_VALUE. VALUE takes precedence.
```

2023-05-17 17:50 UTC, alishaevn requested changes

2023-05-17 17:50 UTC, alishaevn commented on app/services/hyrax/analytics/google.rb
>              REQUIRED_KEYS.all? { |required| config_keys.include?(required) }
```suggestion
            REQUIRED_KEYS.all? { |required| config_keys.include?(required) && @config[required].present? }
```

2023-05-17 17:50 UTC, alishaevn commented on app/services/hyrax/analytics/google.rb
>              REQUIRED_KEYS.all? { |required| config_keys.include?(required) }
make sure that the values actually exist and aren't just empty strings.

2023-05-23 20:42 UTC, alishaevn commented on spec/lib/hyrax/analytics_spec.rb
> +    ENV['GOOGLE_OAUTH_PRIVATE_KEY_VALUE'] = ''
added this line. the rest of the env changes are unifying them with single quotes.

2023-05-23 22:59 UTC, alishaevn commented
each pipeline is failing for the same 2 specs in "spec/lib/hyrax/analytics_spec.rb". those specs are passing locally for me however. may need to check in on the state of circle ci tomorrow per @dlpierce's [comment](https://github.com/samvera/hyrax/pull/5987#issuecomment-1557408157).

![image](https://github.com/samvera/hyrax/assets/29032869/2128546a-faac-427e-9e19-df3393b44ee6)

2023-05-24 23:04 UTC, aprilrieger approved these changes

2023-05-24 23:04 UTC, merged