skip Wings specific `SolrDocumentBehavior` tests if `disable_wings`
samvera/hyrax pull request #6187
Opened 2023-08-24 05:36 UTC by no-reply

@samvera/hyrax-code-reviewers

2023-08-24 15:26 UTC, hackartisan requested changes

2023-08-24 16:03 UTC, no-reply commented on spec/models/concerns/hyrax/solr_document_behavior_spec.rb
>        context 'using non-wings adapter', valkyrie_adapter: :test_adapter do
it took me a minute to understand the question, so hopefully i'm responding to the right thing?

---

there's now code in `spec_helper` that does this `before` block whenever a non-wings adapter is configured via rspec metadata. this was just redundant, so i removed it. the test behavior should be unchanged.

2023-08-30 17:34 UTC, hackartisan requested changes

2023-09-01 17:45 UTC, hackartisan commented on spec/models/concerns/hyrax/solr_document_behavior_spec.rb
>        context 'using non-wings adapter', valkyrie_adapter: :test_adapter do
Thank you @marrus-sh for pointing out that the code fold was messing with me. This seems good.

2023-09-01 17:46 UTC, hackartisan approved these changes

2023-09-01 17:56 UTC, merged