Updates create_child_work_spec.rb for valkyrie.
samvera/hyrax pull request #6428
Opened 2023-11-09 14:32 UTC by bwatson78

### Fixes

Fixes `create_child_work_spec.rb`.

### Summary

Updates create_child_work_spec.rb for valkyrie.

### Type of change (for release notes)

- `notes-valkyrie` Valkyrie Progress

### Changes proposed in this pull request:
* Swaps to valkyrie monographs for work objects.
* Switches to updated sipity entity factory proxy setting.
* Points elements to monograph paths.
* Removes any error messaging or object variables that are ActiveFedora specific.

@samvera/hyrax-code-reviewers

2023-11-09 20:34 UTC, jeremyf submitted a review, later dismissed

2023-11-09 20:40 UTC, dlpierce requested changes
This will reload the object as in the original spec.

2023-11-09 20:40 UTC, dlpierce commented on spec/features/create_child_work_spec.rb
> +      expect(parent.member_ids.count).to eq 1
```suggestion
      expect(Hyrax.query_service.find_by(id: parent.id).member_ids.count).to eq 1
```

2023-11-09 20:40 UTC, dlpierce commented on spec/features/create_child_work_spec.rb
> +      expect(new_parent.member_ids.count).to eq 1
```suggestion
      expect(Hyrax.query_service.find_by(id: parent.id).member_ids.count).to eq 1
      expect(Hyrax.query_service.find_by(id: new_parent.id).member_ids.count).to eq 1
```

2023-11-09 20:40 UTC, dlpierce commented on spec/features/create_child_work_spec.rb
> +        expect(new_parent.member_ids.count).to eq 0
```suggestion
        expect(Hyrax.query_service.find_by(id: new_parent.id).member_ids.count).to eq 0
```

2023-11-09 22:17 UTC, bwatson78 commented
@dlpierce Change requests addressed in https://github.com/samvera/hyrax/pull/6428/commits/36ecee58dcba6be21d1e152a377650c06f37af7d .

2023-11-10 07:51 UTC, dlpierce approved these changes

2023-11-10 07:51 UTC, merged